// Large pool of long exam passages (200–400 words) for rotation
// Categories: government, legal, office, formal writing

export type PassageCategory = "government" | "legal" | "office" | "formal";

export interface Passage {
  id: string;
  category: PassageCategory;
  title: string;
  text: string;
}

export const EXAM_PASSAGES: Passage[] = [
  {
    id: "g1", category: "government", title: "Constitutional Provisions",
    text: "The Constitution of India, adopted on the twenty-sixth day of November nineteen hundred and forty-nine, is the supreme law of the land. It lays down the framework delineating fundamental political principles, establishes the structure, procedures, powers, and duties of government institutions, and sets out fundamental rights, directive principles, and the duties of citizens. It is the longest written constitution of any sovereign country in the world. The constitution was drafted by the Constituent Assembly, which was elected by elected members of the provincial assemblies. Dr Bhimrao Ramji Ambedkar, the chairman of the drafting committee, is widely considered to be its chief architect. The constitution was enacted by the Constituent Assembly on the twenty-sixth of November nineteen forty-nine, and came into effect on the twenty-sixth of January nineteen fifty with a democratic government system, completing the country's transition toward becoming an independent republic. The date, twenty-sixth January, was chosen to commemorate the Purna Swaraj declaration of independence of nineteen thirty. With its adoption, the Union of India officially became the modern and contemporary Republic of India replacing the Government of India Act nineteen thirty-five as the country's fundamental governing document. The Constitution declares India to be a sovereign, socialist, secular, democratic republic, assuring its citizens justice, equality and liberty, and endeavours to promote fraternity among them."
  },
  {
    id: "g2", category: "government", title: "Public Service Commission",
    text: "The Union Public Service Commission is India's central recruiting agency. It is responsible for appointments to and examinations for All India Services and Group A and Group B Central Services. The commission is a constitutional body established under Article three hundred and fifteen of the Constitution of India. The commission consists of a chairman and other members appointed by the President of India. The conditions of service of members of the commission are determined by the President. No minister can be consulted regarding the appointment or salaries of the members of the commission. The commission submits its annual report to the President of India, who causes it to be laid before each House of Parliament. The commission is independent of the executive government and is responsible for ensuring that the civil services of the union are staffed on the basis of merit. It conducts examinations for appointments to the services of the Union and advises on all matters relating to recruitment to civil services and posts, on the principles to be followed in making appointments to civil services and posts, on the suitability of candidates for such appointments, on disciplinary matters affecting a person serving under the Government of India in a civil capacity, and on any other matter referred to them by the President."
  },
  {
    id: "g3", category: "government", title: "SSC Combined Graduate Level",
    text: "The Staff Selection Commission conducts the Combined Graduate Level examination to recruit candidates for various Group B and Group C posts in the various Ministries, Departments and Organizations of the Government of India. The examination consists of multiple tiers designed to assess the candidates on their quantitative ability, English language comprehension, reasoning skills, and general awareness. The candidates who are selected through this examination are posted across various departments of the central government including the Ministry of Finance, the Central Board of Direct Taxes, the Central Board of Indirect Taxes and Customs, the Ministry of Statistics and Programme Implementation, and several others. The typing test forms an integral part of the selection process for posts such as Tax Assistant, Lower Division Clerk, and Data Entry Operator. Candidates are required to type a passage of two hundred words within ten minutes in English or a Hindi passage at a prescribed speed. The accuracy requirement is stringent, allowing only a limited number of errors per hundred words typed. Aspirants are advised to practise extensively on official Government typefaces and to familiarise themselves with the prescribed font size and margin settings specified in the official notification before appearing for the examination. Regular daily practice of at least forty-five minutes to an hour is recommended for achieving the required speed and accuracy levels."
  },
  {
    id: "g4", category: "government", title: "Right to Information Act",
    text: "The Right to Information Act of two thousand and five mandates timely response to citizen requests for government information. The Act empowers citizens, promotes transparency and accountability in the working of the Government, contains corruption, and makes our democracy work for the people in a real sense. It applies to all constitutional authorities, including the executive, legislature and judiciary, and any institution or body established or constituted by an act of Parliament or a state legislature. Under the provisions of this Act, any citizen may request information from a public authority, which is required to reply expeditiously or within thirty days. The Act also requires every public authority to computerise their records for wide dissemination and to proactively publish certain categories of information so that citizens need to approach them for minimum information. The Public Information Officer designated in each public body receives requests for information and is responsible for supplying the information within the prescribed time limit. If the information is not supplied within the prescribed period or if the applicant is not satisfied with the information furnished, he has a right to appeal to a higher authority. The Central Information Commission at the national level and the State Information Commissions at the state level are the appellate bodies that adjudicate disputes arising from the implementation of this Act."
  },
  {
    id: "l1", category: "legal", title: "Civil Procedure Code",
    text: "The Code of Civil Procedure nineteen oh eight is a procedural law relating to the administration of civil proceedings in India. The Code consolidates and amends the laws relating to the procedure of the Courts of Civil Judicature. It contains substantive rules of law applicable in civil matters as well as procedural rules and forms. The Code is divided into two parts, the body of the Code consisting of one hundred and fifty-eight sections and the Schedule consisting of the First Schedule which contains the Orders and Rules, the Second Schedule containing the rules applicable to certain matters, the Third Schedule dealing with execution, and the Fourth Schedule concerning payment and collection. The primary objective of the Code of Civil Procedure is to consolidate and amend the laws relating to the procedure of the courts of civil judicature in India. The Code applies to all civil courts in India below the level of the High Court. Every suit is to be instituted by presenting a plaint to the Court or such officer as it appoints in this behalf. In the plaint, the plaintiff must set out specifically the facts constituting the cause of action and where and when it arose, the facts showing that the Court has jurisdiction, and a statement of the value of the subject matter of the suit for the purposes of jurisdiction and court fees, so far as the case admits of such a statement."
  },
  {
    id: "l2", category: "legal", title: "Indian Penal Code Principles",
    text: "The Indian Penal Code of eighteen sixty provides a general penal code for India. It came into force on the first January eighteen sixty-two. Although the Code has been amended many times since it came into force in eighteen sixty-two, and many new sections have been added to it over the years, most of the original sections still remain in the present Code. The Code is a comprehensive code intended to cover all substantive aspects of criminal law. The Code defines the criminal offences and stipulates the sentences that courts should impose on persons convicted of such offences. The exceptions to criminal liability are codified in the Code itself in the form of the General Exceptions. One of the fundamental principles that the Code is based on is that no act is criminal unless it is done with a guilty mind. The law therefore requires that the accused person must have both committed the prohibited act and must have had the requisite mental element to be guilty of the offence. The Code specifies the mental element required for each offence defined in it. Some offences require intention, some require knowledge, and some are offences of strict liability for which no mental element is required. The Code also penalises attempts to commit crimes and abetment thereof, thereby widening the net of criminal liability to catch those who try to commit offences but do not succeed for reasons beyond their control."
  },
  {
    id: "l3", category: "legal", title: "Court Judgement Transcription",
    text: "This Honourable Court has examined the evidence placed before it by both the learned counsel for the petitioner and the learned counsel appearing on behalf of the respondent State. Having carefully perused the record of the proceedings below and having considered the submissions made at the bar with great care and attention, this Court is of the considered opinion that the impugned order passed by the learned Sessions Judge cannot be sustained in law. The Sessions Court while passing the impugned order has failed to appreciate the vital and clinching evidence placed on record by the petitioner and has erroneously placed reliance on the deposition of witnesses whose testimony is contradictory and inconsistent with the documentary evidence forming part of the record. The doctrine of proof beyond reasonable doubt which is the cornerstone of criminal jurisprudence has not been correctly applied by the court below. The prosecution has failed to establish a complete chain of circumstantial evidence pointing unerringly to the guilt of the accused and excluding every reasonable hypothesis consistent with their innocence. The benefit of doubt, if any, must go to the accused as held by the Supreme Court of India in a catena of decisions. In the circumstances aforesaid, the impugned order of conviction and sentence passed by the learned Sessions Court is hereby set aside. The accused is acquitted of all the charges levelled against him and is directed to be released from custody forthwith, if not required in any other case."
  },
  {
    id: "l4", category: "legal", title: "Contract Law Fundamentals",
    text: "A contract is an agreement enforceable by law. The Indian Contract Act of eighteen seventy-two defines a contract as an agreement enforceable by law. An agreement is every promise and every set of promises forming the consideration for each other. A promise is made when a proposal is accepted. Thus, the following elements must be present for a valid contract to come into existence: there must be an offer or proposal, the offer must be accepted, there must be lawful consideration, the parties must be competent to contract, their consent must be free, the object of the agreement must be lawful, and the agreement must not expressly be declared void. An agreement enforceable by law is a contract. Every promise and every set of promises forming the consideration for each other is an agreement. When one person signifies to another his willingness to do or to abstain from doing anything, with a view to obtaining the assent of that other to such act or abstinence, he is said to make a proposal. When the person to whom the proposal is made signifies his assent thereto, the proposal is said to be accepted. A proposal, when accepted, becomes a promise. When, at the desire of the promisor, the promisee or any other person has done or abstained from doing, or does or abstains from doing, or promises to do or to abstain from doing, something, such act or abstinence or promise is called a consideration for the promise."
  },
  {
    id: "o1", category: "office", title: "Office Administration Manual",
    text: "The efficient management of an office requires a systematic approach to record keeping, correspondence management, and the maintenance of filing systems. All incoming correspondence should be received, stamped with the date of receipt, and entered in the inward register maintained for the purpose. Each letter should be given a unique reference number which facilitates easy retrieval at a later date. The correspondence should then be placed before the concerned officer who will record his directions on a note sheet attached to the file. All outgoing correspondence must be drafted in clear, concise, and grammatically correct language. The draft should be checked for accuracy of facts, correctness of grammar, and adherence to prescribed formats before it is typed for dispatch. The typed letter must be compared with the approved draft to ensure that no errors have crept in during the process of typing. Important documents and files must be kept in a safe and secure location and access should be restricted to authorized personnel only. A comprehensive file index must be maintained and updated regularly to facilitate quick retrieval of documents. Files should be periodically reviewed and those which are no longer required for current business should be transferred to the record room in accordance with the prescribed procedure. A record of such transfer should be maintained in a register kept for the purpose in each section. All employees are responsible for ensuring that the files and documents entrusted to their care are maintained in proper condition."
  },
  {
    id: "o2", category: "office", title: "Official Correspondence Standards",
    text: "Official correspondence constitutes a formal communication between government departments, between government and private parties, or between different organizations. The quality and accuracy of official correspondence reflects the standards and professionalism of the organization concerned. All official letters must conform to the prescribed format and must be addressed to the appropriate authority. The subject line must clearly and concisely indicate the matter to which the letter relates. The body of the letter should be organized in a logical and systematic manner, with each paragraph dealing with a single point or a closely related set of points. Technical terms should be used only when necessary and should be explained if there is any possibility that the recipient may not be familiar with them. The letter should be concluded with an appropriate closing salutation and must bear the designation, name, and contact details of the signatory. It is important that all relevant reference numbers, dates of previous correspondence, and file numbers are quoted in the letter to facilitate easy identification and processing by the recipient. Letters received in response to communications sent must be linked to the original communication and placed on the same file. Acknowledgements must be issued promptly upon receipt of communications that require a detailed response, so that the sender is aware that the communication has been received and is being attended to. Delays in responding to correspondence should be avoided as they create a poor impression and may cause inconvenience to the sender."
  },
  {
    id: "o3", category: "office", title: "Data Entry and Typing Standards",
    text: "Data entry operators and typists working in government offices and private establishments are required to maintain high standards of speed and accuracy in their work. The minimum speed prescribed for most government typing positions is thirty-five words per minute in English and thirty words per minute in Hindi, with an accuracy level of ninety-five per cent or above. These standards represent the minimum requirements and operators are encouraged to achieve higher speeds without compromising on accuracy. Operators should familiarise themselves with the standard keyboard layout and develop the habit of using all ten fingers while typing. The correct finger placement is essential for achieving high speeds, as it reduces the movement of fingers across the keyboard and allows for faster and more accurate typing. The home row keys, that is A S D F for the left hand and J K L semicolon for the right hand, should be the resting position for the fingers. Each finger is assigned specific keys in its vicinity and must be trained to reach those keys quickly and accurately. Operators must not look at the keyboard while typing but should instead maintain their gaze on the source document or the screen. Developing this skill of touch typing is essential for achieving professional typing speeds. Regular practice of at least thirty minutes each day is essential for maintaining and improving typing skills. Operators should practise from different types of documents including legal texts, official correspondence, financial statements, and technical reports to develop versatility."
  },
  {
    id: "f1", category: "formal", title: "Annual Report: Economic Survey",
    text: "The Indian economy demonstrated remarkable resilience during the fiscal year under review, registering a growth rate that exceeded the expectations of most financial analysts and international institutions. The gross domestic product growth was driven primarily by robust performance in the services sector, which accounts for the largest share of the economy's output, and by a sustained recovery in manufacturing activity. The agricultural sector, despite facing challenges in the form of uneven monsoon distribution in certain regions, delivered a creditable performance overall, supported by the government's sustained investment in rural infrastructure and the implementation of price support mechanisms that provided stability to farm incomes. Foreign direct investment inflows reached a record level during the year under review, reflecting the confidence of global investors in the long-term growth potential of the Indian economy. The government's continued focus on improving the ease of doing business, strengthening infrastructure, and promoting digitalization of government services contributed significantly to this outcome. The fiscal deficit was contained within the prescribed limits through a combination of improved tax collection efficiency and rationalisation of government expenditure. The Reserve Bank of India maintained its focus on managing inflation while simultaneously supporting growth through an accommodative monetary policy stance. Going forward, the principal risks to the economic outlook include global geopolitical uncertainties, the possibility of disruptions in energy and commodity markets, and the potential impact of climate-related events on agricultural production and infrastructure."
  },
  {
    id: "f2", category: "formal", title: "Parliamentary Proceedings",
    text: "The Parliament of India consists of the President and the two Houses known respectively as the Council of States, which is also called Rajya Sabha, and the House of the People, which is also called Lok Sabha. The Rajya Sabha is the upper house of the Parliament and consists of not more than two hundred and fifty members, of whom twelve are nominated by the President of India on account of their expertise in fields such as literature, science, art and social service, and the remaining members are elected by the elected members of the State Legislative Assemblies and the Legislative Assemblies of the Union Territories. The Rajya Sabha is not subject to dissolution. One-third of its members retire every two years. Each member is elected for a term of six years. The Lok Sabha or House of the People is the lower house of the Parliament. It is composed of representatives of the people chosen by direct election on the basis of adult suffrage. The maximum strength of the House envisaged by the Constitution is five hundred and fifty-two, up to five hundred and thirty members to represent the territorial constituencies in the States, and up to twenty members to represent the Union Territories. The Lok Sabha, unless sooner dissolved, continues for five years from the date appointed for its first sitting. The primary function of the Parliament is to legislate, approve the financial proposals of the government, and to oversee and hold the government accountable for its actions."
  },
  {
    id: "f3", category: "formal", title: "National Education Policy",
    text: "The National Education Policy of two thousand and twenty represents a comprehensive framework for transforming the educational landscape of India at all levels, from early childhood care and education through higher education. The policy aims to transform India into a vibrant knowledge society and global knowledge superpower by making both school and college education more holistic, flexible, multidisciplinary, suited to twenty-first century needs and aimed at bringing out the unique capabilities of each student. The policy emphasizes the critical importance of early childhood care and education, recognizing it as the foundation of lifelong learning and development. It recommends that all children between the ages of three and six have access to quality early childhood education by the year two thousand and thirty. The medium of instruction in schools should be the home language or mother tongue up to at least Grade Five, and preferably till Grade Eight and beyond, as research has clearly shown that young children learn and grasp non-trivial concepts most quickly in their home language. The policy also emphasizes the importance of the arts, physical education and vocational education in the school curriculum, recognizing that these are essential for the holistic development of students and not secondary to academic subjects. The new policy envisions a restructuring of the current ten plus two school structure into a new five plus three plus three plus four curricular and pedagogical structure, covering the age groups from three to eighteen years."
  },
  {
    id: "f4", category: "formal", title: "Environmental Impact Assessment",
    text: "Environmental impact assessment is a process of evaluating the likely environmental impacts of a proposed project or development, taking into account inter-related socio-economic, cultural and human-health impacts, both beneficial and adverse. The process provides a means of information gathering that enables the competent authority to assess the impacts of a new development on the existing environment. The Environmental Impact Assessment Notification under the Environment Protection Act of nineteen eighty-six makes it mandatory to obtain environmental clearance before undertaking major infrastructure projects. The notification specifies the categories of projects that require environmental clearance and the procedural steps that must be followed in the assessment process. The process involves screening of the project to determine the level of assessment required, scoping to determine the aspects that should be covered in the assessment, carrying out the actual impact assessment, preparation of the environmental impact statement, public consultation and disclosure, decision making by the competent authority, and monitoring during the implementation of the project. Public participation is a fundamental requirement of the environmental impact assessment process. The project proponent is required to publicize the proposed project and provide an opportunity for local communities, civil society organizations, and other interested parties to express their views and concerns. These views must be taken into account in finalizing the assessment and in the decision making process. A dedicated environmental management plan must form part of the clearance and must be implemented throughout the project lifecycle."
  },
  {
    id: "f5", category: "formal", title: "Digital India Initiative",
    text: "The Digital India programme is a flagship programme of the Government of India with a vision to transform India into a digitally empowered society and knowledge economy. The programme was launched with the objective of ensuring that Government services are made available to citizens electronically, people are given access to digital infrastructure as a utility, and there is digital literacy among the citizens of the country. The programme encompasses a wide range of activities, including the development of digital infrastructure, the delivery of government services digitally, and the promotion of digital literacy. Under the programme, several important initiatives have been launched, including the BharatNet project to provide broadband connectivity to all gram panchayats in the country, the DigiLocker service which allows citizens to store their important documents in digital form and share them with government agencies when required, the Unified Payments Interface which has revolutionized digital payments in the country, and the MyGov platform which allows citizens to engage with the government and provide feedback on policies and programmes. The Direct Benefit Transfer programme, which is a component of the Digital India initiative, has transformed the delivery of government subsidies and benefits by enabling the direct transfer of funds to the bank accounts of beneficiaries, eliminating middlemen, reducing leakage, and ensuring that the intended beneficiaries receive the full benefit of government schemes. The programme has contributed significantly to the growth of the digital economy and has made India one of the fastest growing digital markets in the world."
  },
];

const USED_PASSAGES_KEY = "jktm_used_passages";

function getUsedIds(): string[] {
  try { return JSON.parse(localStorage.getItem(USED_PASSAGES_KEY) ?? "[]"); } catch { return []; }
}

function markUsed(id: string) {
  const used = getUsedIds();
  if (!used.includes(id)) {
    const updated = [...used, id].slice(-12);
    localStorage.setItem(USED_PASSAGES_KEY, JSON.stringify(updated));
  }
}

export function getNextPassage(category?: PassageCategory): Passage {
  const pool = category ? EXAM_PASSAGES.filter(p => p.category === category) : EXAM_PASSAGES;
  const used = getUsedIds();
  const available = pool.filter(p => !used.includes(p.id));
  const source = available.length > 0 ? available : pool;
  const idx = Math.floor(Math.random() * source.length);
  const passage = source[idx];
  markUsed(passage.id);
  return passage;
}

export function getPassagesByCategory(category: PassageCategory): Passage[] {
  return EXAM_PASSAGES.filter(p => p.category === category);
}
